export const IMAGE_URL = {
  onboardScreen: require('../assets/png/man.png'),
  avatarImage: require('../assets/png/user.png'),
};

export const SVG_URL = {
  onboardingIcon: require('../assets/svg/onBoarding.svg').default,
  waveSvgIcon: require('../assets/svg/wave.svg').default,
  loginSvgIcon: require('../assets/svg/loginImage.svg').default,
  goggleSvgIcon: require('../assets/svg/goggle.svg').default,
  facebookSvgIcon: require('../assets/svg/facebook.svg').default,
  getProfilePicIcon: require('../assets/svg/picture.svg').default,
  registerSvgIcon: require('../assets/svg/register.svg').default,
  mailSentSvgIcon: require('../assets/svg/mailSent.svg').default,
  emailConfirmIcon: require('../assets/svg/email.svg').default,
  leftChevronIcon: require('../assets/svg/chevronLeft.svg').default,
  downloadIcon: require('../assets/svg/download.svg').default,
  errorIcon: require('../assets/svg/error.svg').default,
  confirmPassword: require('../assets/svg/password.svg').default,
  successIcon: require('../assets/svg/success.svg').default,
  cameraIcon: require('../assets/svg/camera.svg').default,
  galleryIcon: require('../assets/svg/galleryIcon.svg').default,
  imagUploadIcon: require('../assets/svg/imagupload.svg').default,
  dropdownOpen: require('../assets/svg/chevronDown.svg').default,
  dropdownClose: require('../assets/svg/chevronUp.svg').default,
  arrowUp: require('../assets/svg/arrowup.svg').default,
  arrowDown: require('../assets/svg/arrowDown.svg').default,
  homeBarIcon: require('../assets/svg/tabBar/home.svg').default,
  profileBarIcon: require('../assets/svg/tabBar/profile.svg').default,
  goalBarIcon: require('../assets/svg/tabBar/goals.svg').default,
  calenderIcon: require('../assets/svg/calender.svg').default,
  pizzaIcon: require('../assets/svg/expenseDetail/pizza.svg').default,
  airplaneIcon: require('../assets/svg/expenseDetail/airplane.svg').default,
  bookIcon: require('../assets/svg/expenseDetail/book.svg').default,
  carIcon: require('../assets/svg/expenseDetail/car.svg').default,
  cardIcon: require('../assets/svg/expenseDetail/card.svg').default,
  cartIcon: require('../assets/svg/expenseDetail/cart.svg').default,
  filmIcon: require('../assets/svg/expenseDetail/film.svg').default,
  heartIcon: require('../assets/svg/expenseDetail/heart.svg').default,
  homeIcon: require('../assets/svg/expenseDetail/home.svg').default,
  shoppingIcon: require('../assets/svg/expenseDetail/shopping.svg').default,
  piggyBankIcon: require('../assets/svg/expenseDetail/piggy.svg').default,
  defaultIcon: require('../assets/svg/expenseDetail/default.svg').default,
  addExpense: require('../assets/svg/addExpense.svg').default,
  deleteIcon: require('../assets/svg/delete.svg').default,
  noDataImage: require('../assets/svg/noData.svg').default,
  noTransactionSvg: require('../assets/svg/noTransaction.svg').default,
  filterSvg: require('../assets/svg/filter.svg').default,
  checkSvg: require('../assets/svg/check.svg').default,
};

export const LOTTIE_URL = {
  loaderScreen: require('../assets/lottie/loader.json'),
};

export type IconName = keyof typeof SVG_URL;
