export const NavigationConstant = {
  HOME_SCREEN: 'HOME_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  ONBOARD_SCREEN: 'ONBOARD_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  PROFILE_PICTURE_SCREEN: 'PROFILE_PICTURE_SCREEN',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  FORGOT_PASSWORD_EMAIL_SCREEN: 'FORGOT_PASSWORD_EMAIL_SCREEN',
  CHANGE_PASSWORD_SCREEN: 'CHANGE_PASSWORD_SCREEN',
};
