export const NavigationConstant = {
  HOME_SCREEN: 'HOME_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  ONBOARD_SCREEN: 'ONBOARD_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  PROFILE_PICTURE_SCREEN: 'PROFILE_PICTURE_SCREEN',
  VERIFY_OTP_SCREEN: 'VERIFY_OTP_SCREEN',
  FORGOT_PASSWORD_EMAIL_SCREEN: 'FORGOT_PASSWORD_EMAIL_SCREEN',
  CHANGE_PASSWORD_SCREEN: 'CHANGE_PASSWORD_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  ADD_EXPENSE: 'ADD_EXPENSE',
  TRANSACTIONS_SCREEN: 'TRANSACTIONS_SCREEN',
  STATISTICS_SCREEN: 'STATISTICS_SCREEN',
};
