import { IconName } from './imageUrl';

export const DEFAULT_CURRENCIES = [
  { code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳' },
  { code: 'USD', name: 'US Dollar', symbol: '$', flag: '🇺🇸' },
  { code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺' },
  { code: 'GBP', name: 'British Pound', symbol: '£', flag: '🇬🇧' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵' },
  { code: 'AUD', name: 'Australian Dollar', symbol: '$', flag: '🇦🇺' },
  { code: 'CAD', name: 'Canadian Dollar', symbol: '$', flag: '🇨🇦' },
];

// iconList.ts
export const EXPENSE_DETAIL: {
  name: string;
  keywords: string[];
  icon: IconName;
}[] = [
  {
    name: 'Food',
    keywords: [
      'food',
      'pizza',
      'burger',
      'sandwich',
      'pasta',
      'noodles',
      'restaurant',
      'dinner',
      'lunch',
      'breakfast',
      'meal',
      'snack',
      'drink',
      'coffee',
      'tea',
      'beverage',
      'juice',
      'beer',
      'wine',
      'alcohol',
      'bar',
      'pub',
      'fastfood',
      'daru',
      'beer',
      'whiskey',
      'rum',
      'cake',
      'maggie',
      'momo',
      'chips',
    ],
    icon: 'pizzaIcon',
  },
  {
    name: 'Transport',
    keywords: [
      'transport',
      'uber',
      'ola',
      'cab',
      'taxi',
      'car',
      'bus',
      'train',
      'metro',
      'flight',
      'plane',
      'bike',
      'scooter',
      'fuel',
      'petrol',
      'diesel',
      'gas',
      'parking',
      'toll',
    ],
    icon: 'carIcon',
  },
  {
    name: 'Groceries',
    keywords: [
      'grocery',
      'groceries',
      'supermarket',
      'mart',
      'store',
      'vegetable',
      'veg',
      'fruit',
      'fruits',
      'apple',
      'banana',
      'orange',
      'mango',
      'grapes',
      'milk',
      'curd',
      'yogurt',
      'butter',
      'cheese',
      'bread',
      'egg',
      'rice',
      'flour',
      'atta',
      'dal',
      'lentil',
      'oil',
      'sugar',
      'salt',
      'spice',
      'masala',
      'chicken',
      'meat',
      'fish',
      'seafood',
    ],
    icon: 'shoppingIcon',
  },
  {
    name: 'Rent',
    keywords: [
      'rent',
      'house',
      'room',
      'apartment',
      'flat',
      'pg',
      'hostel',
      'lease',
      'home',
    ],
    icon: 'homeIcon',
  },
  {
    name: 'Entertainment',
    keywords: [
      'entertainment',
      'movie',
      'cinema',
      'netflix',
      'prime',
      'hotstar',
      'spotify',
      'game',
      'concert',
      'party',
      'club',
      'event',
      'theatre',
      'fun',
      'music',
      'show',
      'amazon',
      'youtube',
    ],
    icon: 'filmIcon',
  },
  {
    name: 'Travel',
    keywords: [
      'travel',
      'trip',
      'vacation',
      'holiday',
      'tour',
      'hotel',
      'resort',
      'ticket',
      'visa',
      'passport',
      'tourism',
      'beach',
      'mountain',
      'flight',
      'bus',
      'train',
    ],
    icon: 'airplaneIcon',
  },
  {
    name: 'Shopping',
    keywords: [
      'shopping',
      'mall',
      'clothes',
      'fashion',
      'shoes',
      'bag',
      'cosmetics',
      'makeup',
      'jewellery',
      'electronics',
      'gadget',
      'mobile',
      'laptop',
      'furniture',
      'Tshirt',
      'Pen',
    ],
    icon: 'shoppingIcon',
  },
  {
    name: 'Health',
    keywords: [
      'health',
      'doctor',
      'hospital',
      'clinic',
      'medicine',
      'tablet',
      'syrup',
      'pharmacy',
      'medical',
      'dentist',
      'checkup',
      'gym',
      'fitness',
      'workout',
      'exercise',
      'protein',
      'supplement',
      'cult',
    ],
    icon: 'heartIcon',
  },
  {
    name: 'Education',
    keywords: [
      'education',
      'school',
      'college',
      'university',
      'tuition',
      'course',
      'class',
      'coaching',
      'exam',
      'fees',
      'study',
      'book',
      'library',
    ],
    icon: 'bookIcon',
  },
  {
    name: 'Bills',
    keywords: [
      'bill',
      'bills',
      'electricity',
      'water',
      'gas',
      'internet',
      'wifi',
      'recharge',
      'mobile',
      'postpaid',
      'prepaid',
      'phone',
      'subscription',
      'loan',
      'emi',
    ],
    icon: 'cardIcon',
  },
  {
    name: 'Savings',
    keywords: [
      'saving',
      'savings',
      'investment',
      'stock',
      'share',
      'mutual',
      'fund',
      'bank',
      'deposit',
      'gold',
      'crypto',
      'nft',
      'insurance',
    ],
    icon: 'piggyBankIcon',
  },
  {
    name: 'Other',
    keywords: ['other', 'misc', 'general', 'uncategorized', 'etc', 'random'],
    icon: 'defaultIcon',
  },
];

export const filterKeyword = [
  {
    id: 1,
    filterName: 'Sort by Date Ascending',
    value: 'dateAscending',
  },
  {
    id: 2,
    filterName: 'Sort by Date Descending',
    value: 'dateDescending',
  },
  {
    id: 3,
    filterName: 'Sort by Amount Ascending',
    value: 'amountAscending',
  },
  {
    id: 4,
    filterName: 'Sort by Amount Descending',
    value: 'amountDescending',
  },
];
