export const STRING_CONFIG = {
  onboarding: {
    headingOne: 'Spend Smarter',
    HeadingTwo: 'Save More',
  },
  genricString: {
    login: 'Login',
    loginNavText: ' Already Have Account?',
    getStartedText: 'Get Started',
  },
  authScreenString: {
    headingOne: 'Track it. Save it. Enjoy it.',
    welcomeText: 'Welcome Back',
    welcomeSubText: 'Enter your Details Below',
    siginBtnText: 'Sign In',
    forgetPasswordText: 'Forgot your password ?',
    footerText: 'Or sign in with ',
    goggleText: 'Google',
    FaceBookText: 'Facebook',
    forgetPasswordHeaderText: 'We’ve sent a 6-digit code to your Number',
  },
  RegisterScreenString: {
    openCameraBtnText: 'Say Cheese 📸',
    headerOne: 'Snap to Complete \n Your  Profile',
    subheadigTwo: 'Make sure your face is clearly visible and well-lit',
    RegisterHeading: 'Sign up now and set up your monthly plan in minutes.',
    RegisterSubHeading: 'Start Your Budget Journey',
    RegisterBtnText: 'Start My Journey',
  },
  basicInfoString: {
    fullName: 'Enter your full name',
    emailAddress: 'Enter your email',
    phoneNumber: 'Enter your phone number',
    password: 'Create a password',
    confirmPassword: 'Re-enter your password',
  },
  forgetPasswordString: {
    header: 'Forgot Password',
    headerOne: 'Please enter your Phone Number To ',
    headerTwo: 'receive a verification code',
    mailSent: 'Send',
  },
  modalText: {
    errorNetworkModal: {
      headerOne: 'Something went wrong.',
      headerTwo: 'Please enter Email And Password',
      btnText: 'Try Again',
      otpError: 'Please Enter A Valid OTP',
      successHeader: 'congratulations',
      successFooter: '🎉 Password reset successful',
      passwordFailure: 'Password and confirm password do not match',
    },
  },
  errorText: {
    emailError: 'Please enter proper Email format',
    passwordError: 'Password must be at least 6 characters',
    emptyError: 'Please enter your phone number',
    phoneError: 'Please enter a valid phone number',
    otpEmptyError: 'Please enter OTP',
  },
};
